-- =============================================================
-- Migration 023: Top Priorities for the session report.
--
-- Extends player_coaching_themes (added in 019) with a "priority" kind
-- alongside the existing "theme" rows. Priorities are the 3-5 ranked
-- things the player should work on, generated by AI but coach-editable.
--
-- Key requirement: ALWAYS preserve the original AI-generated text even
-- after a coach edits it, so we can later train / learn from the
-- coach's edits. We snapshot AI output into ai_original_* columns at
-- generation time; coach edits only touch the live title/problem/
-- solution fields. Every edit is also journaled into
-- coaching_theme_edits for full history.
-- =============================================================

ALTER TABLE player_coaching_themes
    ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'theme'
        CHECK (kind IN ('priority','theme')),
    ADD COLUMN IF NOT EXISTS priority_rank INT,
    -- AI-supplied evidence pointers — the chips that show under the card
    -- (e.g. {"key":"stat.kitchen_arrival.serving","label":"42% kitchen arrival on serve"}).
    ADD COLUMN IF NOT EXISTS evidence_chips JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Frozen original AI version. Populated once at generation; never
    -- overwritten by coach edits.
    ADD COLUMN IF NOT EXISTS ai_original_title    TEXT,
    ADD COLUMN IF NOT EXISTS ai_original_problem  TEXT,
    ADD COLUMN IF NOT EXISTS ai_original_solution TEXT,
    ADD COLUMN IF NOT EXISTS ai_model             TEXT,
    ADD COLUMN IF NOT EXISTS ai_generated_at      TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_themes_session_player_kind
    ON player_coaching_themes(session_id, player_id, kind, priority_rank);

-- Per-edit journal. Lets us replay how a coach changed an AI
-- recommendation, and gives a corpus to train future prompts on.
CREATE TABLE IF NOT EXISTS coaching_theme_edits (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    theme_id    UUID NOT NULL REFERENCES player_coaching_themes(id) ON DELETE CASCADE,
    org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    edited_by   UUID,
    -- 'title' | 'problem' | 'solution' | 'priority_rank' | 'deleted' | 'created'
    field       TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    edited_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_theme_edits_theme ON coaching_theme_edits(theme_id);
CREATE INDEX IF NOT EXISTS idx_theme_edits_org   ON coaching_theme_edits(org_id);

ALTER TABLE coaching_theme_edits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "read theme edits" ON coaching_theme_edits
    FOR SELECT USING (has_org_access(org_id));

CREATE POLICY "coaches write theme edits" ON coaching_theme_edits
    FOR ALL
    USING (is_coach(org_id))
    WITH CHECK (is_coach(org_id));
